---

###########################################################################################
# This file calls the OS specific tasks to configure HANA specific clustering resources  #8
###########################################################################################

# 1. Design the role 5.5.4.0-cluster one into all the actions upto cluster roles defenition including installation
# 2. create a separate task which has common AASCS profile changes actions which could be used for both sles/rhel
# 3. create os based cluster resources yaml where you actually create the cluster resources

# Clustering commands are based on the Host OS

- name:                                "ERS Install: check if installed"
  ansible.builtin.stat:
    path:                              /etc/sap_deployment_automation/sap_deployment_ers.txt
  register:                            ers_installed

- name:                                "ASCS HA Install: check if installed"
  ansible.builtin.stat:
    path:                              /etc/sap_deployment_automation/sap_deployment_ASCS.txt
  register:                            ASCS_installed

- name:                                "5.6 ASCSERS - Cluster based on OS in VM"
  ansible.builtin.include_tasks:       "5.6.4.0-cluster-{{ ansible_os_family }}.yml"
  when:                                (not ASCS_installed.stat.exists) or (not ers_installed.stat.exists)

# introduce throttle to sequence task execution on each node before moving to next task
# did not add the cluster includes in here. May need to consider this here as well.
# ansible.builtin.stat fails with dict object has no attribute 'stat', because the
# dict doesn't have any values as the exec on primary node is skipped and
# registered post_[ASCS/ers] vars are empty not dictionaries
- name:                                "5.6 ASCSERS - Adapt the AASCS/ASCS and ERS instance profiles"
  throttle:                            1
  block:
    - name:                            "Post ASCS HA Install: check if installed"
      become:                          true
      ansible.builtin.stat:
        path:                          "/etc/sap_deployment_automation/{{ sap_sid | upper }}/sap_deployment_ASCS.txt"
      register:                        post_ASCS_install
      failed_when:                     not post_ASCS_install.stat.exists
      when:                            ansible_hostname == primary_instance_name

    - name:                            "Post ERS Install: check if installed"
      become:                          true
      ansible.builtin.stat:
        path:                          "/etc/sap_deployment_automation/{{ sap_sid | upper }}/sap_deployment_ers.txt"
      register:                        post_ers_install
      failed_when:                     not post_ers_install.stat.exists
      when:                            ansible_hostname == secondary_instance_name

- name:                                "5.6 ASCSERS - profile"
  ansible.builtin.include_tasks:       "5.6.4.1-ASCSersprofile.yaml"

- name:                                "5.6 ASCSERS - resources"
  ansible.builtin.include_tasks:       "5.6.4.2-sap-resources-{{ ansible_os_family }}.yml"
  # when:
  #   - ersservicehalib.rc == 0
  #   - ASCSservicehalib.rc == 0

...
