---

# SLES Clustering - Deploy AASCS/ERS clustering Resources
# Ref: https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-rhel-netapp-files


 # [1] Create a virtual IP resource and health-probe for the AASCS instance

- name:                                "5.6 ASCSERS - SUSE - ASCS - Cluster Configuration before Install "
  throttle:                            1
  block:
    - name :                           "Put Secondary host on standby"
      ansible.builtin.command:         crm node standby {{ secondary_instance_name }}

    - name:                            "5.6 ASCSERS - ASCS - Configure File system resources"
      ansible.builtin.command: >
                                       crm configure primitive fs_{{ sap_sid }}_AASCS Filesystem \
                                       device='{{ sap_mnt }}/usrsap{{ sap_sid }}aASCS{{ ASCS_instance_number }}' \
                                       directory='/usr/sap/{{ sap_sid | upper }}/AASCS{{ ASCS_instance_number }}' fstype='nfs' options='sec=sys,vers=4.1' \
                                       op start timeout="{{ cluster_sap_ASCS_timeouts.start }}" interval=0 \
                                       op stop timeout="{{ cluster_sap_ASCS_timeouts.stop }}"  interval=0 \
                                       op monitor interval="20s" timeout="40s"
      register:                        aASCS_fs_resource
      failed_when:                     aASCS_fs_resource.rc > 1

    - name:                            "5.6 ASCSERS - ASCS - Create AASCS VIP - This is LB frontend AASCS/ASCS IP"
      ansible.builtin.command: >
                                       crm configure primitive vip_{{ sap_sid }}_AASCS IPaddr2 \
                                       params ip={{ ASCS_lb_ip }} cidr_netmask={{ subnet_prefix }} \
                                       op monitor interval="10s" timeout="20s"
      register:                        aASCS_vip
      failed_when:                     aASCS_vip.rc > 1

    - name:                            "5.6 ASCSERS - ASCS - create Azure LB resource"
      ansible.builtin.command:         crm configure primitive nc_{{ sap_sid }}_AASCS azure-lb port=620{{ ASCS_instance_number }}
      register:                        aASCS_lb
      failed_when:                     aASCS_lb.rc > 1

    - name:                            "5.6 ASCSERS - ASCS - Create Health Probe"
      ansible.builtin.command: >
                                       crm configure group g-{{ sap_sid }}_AASCS fs_{{ sap_sid }}_AASCS nc_{{ sap_sid }}_AASCS \
                                       vip_{{ sap_sid }}_AASCS meta resource-stickiness=3000
      register:                        aASCS_hp
      failed_when:                     aASCS_hp.rc > 1
  when: inventory_hostname == primary_instance_name

- name:                                "5.6 ASCSERS - SUSE - ASCS - Install ASCS on Primary host"
  throttle:                            1
  block:
    # [1] Install SAP NetWeaver AASCS - here we can call the ASCS installation playbook -
    - name:                            "5.6 ASCSERS - ASCS - Assign ownership"
      ansible.builtin.file:
        path:                          "{{ item.path }}"
        owner:                         "{{ sap_sid | lower }}adm"
        group:                         sapsys
        recurse:                       true
        state:                         directory
      loop:
        - { path: '/sapmnt/{{ sap_sid | upper }}' }
        - { path: '/usr/sap/{{ sap_sid | upper }}/SYS' }
        - { path: '/usr/sap/{{ sap_sid | upper }}/AASCS{{ ASCS_instance_number }}' }

    - name:                            "5.6 ASCSERS - ASCS - Install ASCS on Primary host"
      ansible.builtin.include_role:
        name:                          roles-sap/5.0.1-ASCS-ha-install
      vars:
        sap_ASCS_hostname:              "{{ ASCS_virtual_hostname }}"
  when: inventory_hostname == primary_instance_name

# [1] Create a virtual IP resource and health-probe for the ERS instance

- name:                                "5.6 ASCSERS - SUSE - ERS - Cluster Configuration before Install"
  throttle:                            1
  block:
    - name:                            "5.6 ASCSERS - ERS - Bring Secondary host online"
      ansible.builtin.command:         crm node online {{ secondary_instance_name }}
      register:                        secondary_online
      changed_when:                    secondary_online.rc != 0

    - name :                           "5.6 ASCSERS - ERS - Put Primary host on standby"
      ansible.builtin.command:         crm node standby {{ primary_instance_name }}
      register:                        primary_standby
      changed_when:                    primary_standby.rc != 0

    - name:                            "5.6 ASCSERS - ERS - Configure File system resources"
      ansible.builtin.command: >
                                       crm configure primitive fs_{{ sap_sid }}_ERS Filesystem \
                                       device='{{ sap_mnt }}/usrsap{{ sap_sid }}ers{{ ers_instance_number }}' \
                                       directory='/usr/sap/{{ sap_sid | upper }}/ERS{{ ers_instance_number }}' fstype='nfs' options='sec=sys,vers=4.1' \
                                       op start timeout="{{ cluster_sap_ASCS_timeouts.start }}" interval=0 \
                                       op stop timeout="{{ cluster_sap_ASCS_timeouts.stop }}"  interval=0 \
                                       op monitor interval="20s" timeout="40s"
      register:                        ers_fs_resource
      failed_when:                     ers_fs_resource.rc > 1

    - name:                            "5.6 ASCSERS - ERS - Create ERS VIP - This is LB frontend ERS IP"
      ansible.builtin.command: >
                                       crm configure primitive vip_{{ sap_sid }}_ERS IPaddr2 \
                                       params ip={{ ers_lb_ip }} cidr_netmask={{ subnet_prefix }} \
                                       op monitor interval="10s" timeout="20s"
      register:                        ers_vip
      failed_when:                     ers_vip.rc > 1

    - name:                            "5.6 ASCSERS - ERS - create Azure LB resource "
      ansible.builtin.command:         crm configure primitive nc_{{ sap_sid }}_ERS azure-lb port=621{{ ers_instance_number }}
      register:                        ers_alb
      failed_when:                     ers_alb.rc > 1

    - name:                            "5.6 ASCSERS - ERS - Create Health Probe"
      ansible.builtin.command: >
                                       crm configure group g-{{ sap_sid }}_ERS fs_{{ sap_sid }}_ERS nc_{{ sap_sid }}_ERS \
                                       vip_{{ sap_sid }}_ERS meta resource-stickiness=3000
      register:                        ers_hp
      failed_when:                     ers_hp.rc > 1
  when: inventory_hostname == secondary_instance_name

    # [2] Install SAP NetWeaver ERS - Create a new playbook for Installation of ERS - done
- name:                                "5.6 ASCSERS - SUSE - ERS - Install ERS on Secondary host"
  throttle:                            1
  block:
    - name:                            "5.6 ASCSERS - ERS - Assign ownership"
      ansible.builtin.file:
        path:                          "{{ item.path }}"
        owner:                         "{{ sap_sid | lower }}adm"
        group:                         sapsys
        recurse:                       true
        state:                         directory
      loop:
        - { path: '/sapmnt/{{ sap_sid | upper }}' }
        - { path: '/usr/sap/{{ sap_sid | upper }}/SYS' }
        - { path: '/usr/sap/{{ sap_sid | upper }}/ERS{{ ers_instance_number }}' }

    - name:                            "5.6 ASCSERS - ERS - Install on Secondary host"
      ansible.builtin.include_role:
        name:                          roles-sap/5.0.2-ers-ha-install
  always:
    - name:                            "5.6 ASCSERS - ERS - Bring Primary host online"
      ansible.builtin.command:         "crm node online {{ primary_instance_name }}"
      register:                        primary_online
      changed_when:                    primary_online.rc != 0
  when: inventory_hostname == secondary_instance_name


# END of playbook.
...
