---

cluster_totem:
  token: 30000
  retransmits: 10
  join: 60
  consensus: 36000
  max_messages: 20

cluster_quorum:
  expected_votes: 2
  two_node: 1

# These are the default timeouts used for the SAP ASCS OS clustering. Depending on the
# SAP ASCS System, these may need to be adjusted if the operation takes longer than expected.
cluster_sap_ASCS_timeouts:
  start:          60s
  stop:           60s
  monitor_master: 700
  monitor_slave: 700
  promote: 3600
  demote: 3600

cluster_status_cmd:
  RedHat: "pcs status --full"
  Suse: "crm status full"

cluster_status_report_wait_in_s: 60

# The following values should be same as iASCSI configuration
# run 'sudo targetcli ls' on iASCSI target virtual machines to get all iASCSI configuration
cluster_name: nw{{ sid | lower }}
# storage_object: sbd{{ cluster_name }}
# target: "{{ iASCSi_object }}.{{ cluster_name }}.local:{{ cluster_name }}"

# SAP AASCS/ERS Utility Commands
sapcontrolASCS_command: "sapcontrol -nr {{ ASCS_instance_number }}"
sapcontrolers_command: "sapcontrol -nr {{ ers_instance_number }}"

# hana_stop_start_timeout_in_seconds: 2700
# hana_stop_start_delay_in_seconds: 2
...
