---

# TODO: The below lists are enough for the ASCS being configured for the Bill of Materials processing.
#       The lists will need expanding to cover all expected disks/mount points for all hosts.
#       This will likely include NFS mounts, and will need to consider different deployment sizes/configurations.

# sap_volume_groups:
#   - { tier: 'all', vg: vg_sap,  pvs: /dev/disk/azure/ASCSi1/lun0 }

# sap_logical_volumes:
#   - { tier: 'all', lv: 'lv_usrsap',        vg: 'vg_sap', size: '64g',      opts: '' }
#   - { tier: 'ASCS', lv: 'lv_sapmnt',        vg: 'vg_sap', size: '128g',     opts: '' }
#   - { tier: 'ASCS', lv: 'lv_usrsapinstall', vg: 'vg_sap', size: '100%FREE', opts: '' }
#   - { tier: 'web', lv: 'lv_sapmnt',        vg: 'vg_sap', size: '1g',       opts: '' }

# sap_filesystems:
#   - { tier: 'all', fstype: 'xfs', dev: '/dev/vg_sap/lv_usrsap',        mount_path: '/usr/sap' }
#   - { tier: 'ASCS', fstype: 'xfs', dev: '/dev/vg_sap/lv_sapmnt',        mount_path: '/sapmnt' }
#   - { tier: 'ASCS', fstype: 'xfs', dev: '/dev/vg_sap/lv_usrsapinstall', mount_path: '{{ target_media_location }}' }
#   - { tier: 'web', fstype: 'xfs', dev: '/dev/vg_sap/lv_sapmnt',        mount_path: '/sapmnt' }

# sap_swap:
#   - { tier: 'ASCS',  swap_size_mb: '20480' }
#   - { tier: 'pas',  swap_size_mb: '20480' }
#   - { tier: 'app',  swap_size_mb: '20480' }
#   - { tier: 'web',  swap_size_mb: '20480' }
#   - { tier: 'hana', swap_size_mb: '2048' }
