# Tasks:
#   OS: hosts file, Entries - /etc/hosts
#
# TODO:

---


# -------------------------------------+---------------------------------------8
#
# Description:  Validation for Prerequisites
#
- name:                                "2.4 Hosts: - import pre_checks"
  ansible.builtin.import_tasks:        pre_checks.yaml
# -------------------------------------+---------------------------------------8

#   OS: hosts file, Entries - /etc/hosts
- name:                                "2.4 Hosts: - OS: Common, Entries - /etc/hosts"
  ansible.builtin.blockinfile:
    path:                              /etc/hosts
    mode:                              0644
    create:                            true
    backup:                            true
    state:                             present
    block:                             "{{ lookup('file', 'hosts.block') }}"
    marker:                            "# {mark} ANSIBLE MANAGED BLOCK - COMMON"


- name:                                "2.4 Hosts: - OS: SID, Entries - /etc/hosts"
  ansible.builtin.blockinfile:
    path:                              /etc/hosts
    mode:                              0644
    create:                            true
    state:                             present
    block:                             "{{ lookup('template', 'hosts.j2') }}"
    marker:                            "# {mark} ANSIBLE MANAGED BLOCK - {{ sap_sid | upper }}"

- name:                                "2.4 Hosts: - Set the ASCS and ERS Virtual Instance hostname"
  ansible.builtin.set_fact:
    ASCS_virtual_hostname:              "{{ sap_sid | lower }}ASCS{{ ASCS_instance_number }}cl1"
    ers_virtual_hostname:              "{{ sap_sid | lower }}ers{{ ers_instance_number }}cl2"
    db_virtual_hostname:               "{{ sap_sid | lower }}{{ db_sid | lower }}db{{ db_instance_number }}cl"
  when:
    - ASCS_high_availability or db_high_availability

- name:                                "2.4 Hosts: - Get the Server name list"
  ansible.builtin.set_fact:
    ASCS_server_list:                   "{{ ASCS_server_list | default([]) + [item] }}"
  with_items:
    - "{{ query('inventory_hostnames', '{{ sap_sid | upper }}_ASCS') }}"


- name:                                "2.4 Hosts: - Setup Virtual host name resolution - ASCS & ERS"
  ansible.builtin.blockinfile:
    path:                              /etc/hosts
    mode:                              0644
    create:                            true
    state:                             present
    block: |
      {{ '%-19s' | format(ASCS_lb_ip) }} {{ '%-50s' | format(ASCS_virtual_hostname + '.' + sap_fqdn) }} {{ '%-21s' | format(ASCS_virtual_hostname) }}
      {{ '%-19s' | format(ers_lb_ip) }} {{ '%-50s' | format(ers_virtual_hostname + '.' + sap_fqdn) }} {{ '%-21s' | format(ers_virtual_hostname) }}
    marker:                            "# {mark} AASCS/ERS Entries {{ ASCS_virtual_hostname }}"
  when:
    - ASCS_high_availability
    - ASCS_server_list | length > 0

- name:                                "2.4 Hosts: - Setup Virtual host name resolution - DB"
  ansible.builtin.blockinfile:
    path:                              /etc/hosts
    mode:                              0644
    create:                            true
    state:                             present
    block: |
      {{ '%-19s' | format(db_lb_ip) }} {{ '%-50s' | format(db_virtual_hostname + '.' + sap_fqdn) }} {{ '%-21s' | format(db_virtual_hostname) }}
    marker:                            "# {mark} DB Entries {{ db_virtual_hostname }}"
  when:
    - db_high_availability
    - platform == 'HANA'

- name:                                "2.4 Hosts: - Setup Virtual host name resolution - DB"
  ansible.builtin.blockinfile:
    path:                              /etc/hosts
    mode:                              0644
    create:                            true
    state:                             present
    block: |
      {{ '%-19s' | format(db_lb_ip) }} {{ '%-50s' | format(db_virtual_hostname + '.' + sap_fqdn) }} {{ '%-21s' | format(db_virtual_hostname) }}
    marker:                            "# {mark} DB Entries {{ db_virtual_hostname }}"
  when:
    - db_high_availability
    - platform == 'DB2'

...
