---
# TODO: Maybe move these to a group_vars/all/distro file so that they
# can be shared by all playbooks/tasks automatically, and extend with
# standardised versions of all similar patterns used in the playbooks.
distro_name:                           "{{ ansible_os_family | upper }}-{{ ansible_distribution_major_version }}"
distribution_id:                       "{{ ansible_os_family | lower ~ ansible_distribution_major_version }}"
distribution_full_id:                  "{{ ansible_os_family | lower ~ ansible_distribution_version }}"

ASCS_virtual_hostname:                  "{{ sap_sid | lower }}ASCS{{ ASCS_instance_number }}cl1"
ers_virtual_hostname:                  "{{ sap_sid | lower }}ers{{ ers_instance_number }}cl2"
iASCSi_object:                          iqn.2006-04

iASCSi_port:                            3260
