---

ASCS_virtual_hostname: "{% if ASCS_high_availability is defined %}{{ sap_sid | lower }}ASCS{{ ASCS_instance_number }}cl1{% else %}{{ hostvars[query('inventory_hostnames', '{{ sap_sid | upper }}_ASCS')]['virtual_host'] | first }}{% endif %}"
